name: flutter_iot_wifi
description: Connect to an IoT access point using Android or iOS
version: 0.0.3
homepage: https://github.com/MousyBusiness/flutter_iot_wifi
repository: https://github.com/MousyBusiness/flutter_iot_wifi

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.mousybusiness.flutter_iot_wifi
        pluginClass: FlutterIotWifiPlugin
      ios:
        pluginClass: FlutterIotWifiPlugin

